In [17]:
pip install selenium

Collecting selenium
  Downloading selenium-4.47.0-py3-none-any.whl.metadata (7.4 kB)
Requirement already satisfied: certifi>=2026.2.25 in c:\Users\Doctor Laptop\AppData\Local\Programs\Python\Python314\Lib\site-packages (from selenium) (2026.7.22)
Collecting trio<1.0,>=0.31.0 (from selenium)
  Downloading trio-0.34.0-py3-none-any.whl.metadata (8.5 kB)
Collecting trio-websocket<1.0,>=0.12.2 (from selenium)
  Downloading trio_websocket-0.12.2-py3-none-any.whl.metadata (5.1 kB)
Requirement already satisfied: typing_extensions<5.0,>=4.15.0 in C:\Users\Doctor Laptop\AppData\Roaming\Python\Python314\site-packages (from selenium) (4.16.0)
Requirement already satisfied: urllib3<3.0,>=2.6.3 in c:\Users\Doctor Laptop\AppData\Local\Programs\Python\Python314\Lib\site-packages (from urllib3[socks]<3.0,>=2.6.3->selenium) (2.7.0)
Collecting websocket-client<2.0,>=1.8.0 (from selenium)
  Downloading websocket_client-1.9.0-py3-none-any.whl.metadata (8.3 kB)
Collecting attrs>=23.2.0 (from trio<1.0,>=0.31.0->selenium)
  Using cached attrs-26.1.0-py3-none-any.whl.metadata (8.8 kB)
Collecting sortedcontainers (from trio<1.0,>=0.31.0->selenium)
  Downloading sortedcontainers-2.4.0-py2.py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: idna in c:\Users\Doctor Laptop\AppData\Local\Programs\Python\Python314\Lib\site-packages (from trio<1.0,>=0.31.0->selenium) (3.19)
Collecting outcome (from trio<1.0,>=0.31.0->selenium)
  Downloading outcome-1.3.0.post0-py2.py3-none-any.whl.metadata (2.6 kB)
Collecting sniffio>=1.3.0 (from trio<1.0,>=0.31.0->selenium)
  Downloading sniffio-1.3.1-py3-none-any.whl.metadata (3.9 kB)
Collecting cffi>=1.14 (from trio<1.0,>=0.31.0->selenium)
  Downloading cffi-2.1.1-cp314-cp314-win_amd64.whl.metadata (2.6 kB)
Collecting wsproto>=0.14 (from trio-websocket<1.0,>=0.12.2->selenium)
  Downloading wsproto-1.3.2-py3-none-any.whl.metadata (5.2 kB)
Collecting pysocks!=1.5.7,<2.0,>=1.5.6 (from urllib3[socks]<3.0,>=2.6.3->selenium)
  Downloading PySocks-1.7.1-py3-none-any.whl.metadata (13 kB)
Collecting pycparser (from cffi>=1.14->trio<1.0,>=0.31.0->selenium)
  Using cached pycparser-3.0-py3-none-any.whl.metadata (8.2 kB)
Collecting h11<1,>=0.16.0 (from wsproto>=0.14->trio-websocket<1.0,>=0.12.2->selenium)
  Using cached h11-0.16.0-py3-none-any.whl.metadata (8.3 kB)
Downloading selenium-4.47.0-py3-none-any.whl (9.5 MB)
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.5 MB 2.1 MB/s eta 0:00:05
   --- ------------------------------------ 0.8/9.5 MB 1.5 MB/s eta 0:00:06
   --- ------------------------------------ 0.8/9.5 MB 1.5 MB/s eta 0:00:06
   ---- ----------------------------------- 1.0/9.5 MB 1.1 MB/s eta 0:00:08
   ---- ----------------------------------- 1.0/9.5 MB 1.1 MB/s eta 0:00:08
   ---- ----------------------------------- 1.0/9.5 MB 1.1 MB/s eta 0:00:08
   ----- ---------------------------------- 1.3/9.5 MB 862.9 kB/s eta 0:00:10
   ----- ---------------------------------- 1.3/9.5 MB 862.9 kB/s eta 0:00:10
   ----- ---------------------------------- 1.3/9.5 MB 862.9 kB/s eta 0:00:10
   ----- ---------------------------------- 1.3/9.5 MB 862.9 kB/s eta 0:00:10
   ----- ---------------------------------- 1.3/9.5 MB 862.9 kB/s eta 0:00:10
   ------ --------------------------------- 1.6/9.5 MB 575.7 kB/s eta 0:00:14
   ------ --------------------------------- 1.6/9.5 MB 575.7 kB/s eta 0:00:14
   ------ --------------------------------- 1.6/9.5 MB 575.7 kB/s eta 0:00:14
   ------ --------------------------------- 1.6/9.5 MB 575.7 kB/s eta 0:00:14
   ------ --------------------------------- 1.6/9.5 MB 575.7 kB/s eta 0:00:14
   ------- -------------------------------- 1.8/9.5 MB 458.7 kB/s eta 0:00:17
   ------- -------------------------------- 1.8/9.5 MB 458.7 kB/s eta 0:00:17
   ------- -------------------------------- 1.8/9.5 MB 458.7 kB/s eta 0:00:17
   ------- -------------------------------- 1.8/9.5 MB 458.7 kB/s eta 0:00:17
   ------- -------------------------------- 1.8/9.5 MB 458.7 kB/s eta 0:00:17
   ------- -------------------------------- 1.8/9.5 MB 458.7 kB/s eta 0:00:17
   ------- -------------------------------- 1.8/9.5 MB 458.7 kB/s eta 0:00:17
   ------- -------------------------------- 1.8/9.5 MB 458.7 kB/s eta 0:00:17
   ------- -------------------------------- 1.8/9.5 MB 458.7 kB/s eta 0:00:17
   ------- -------------------------------- 1.8/9.5 MB 458.7 kB/s eta 0:00:17
   ------- -------------------------------- 1.8/9.5 MB 458.7 kB/s eta 0:00:17
   -------- ------------------------------- 2.1/9.5 MB 329.6 kB/s eta 0:00:23
   -------- ------------------------------- 2.1/9.5 MB 329.6 kB/s eta 0:00:23
   -------- ------------------------------- 2.1/9.5 MB 329.6 kB/s eta 0:00:23
   -------- ------------------------------- 2.1/9.5 MB 329.6 kB/s eta 0:00:23
   -------- ------------------------------- 2.1/9.5 MB 329.6 kB/s eta 0:00:23
   -------- ------------------------------- 2.1/9.5 MB 329.6 kB/s eta 0:00:23
   -------- ------------------------------- 2.1/9.5 MB 329.6 kB/s eta 0:00:23
   -------- ------------------------------- 2.1/9.5 MB 329.6 kB/s eta 0:00:23
   -------- ------------------------------- 2.1/9.5 MB 329.6 kB/s eta 0:00:23
   -------- ------------------------------- 2.1/9.5 MB 329.6 kB/s eta 0:00:23
   -------- ------------------------------- 2.1/9.5 MB 329.6 kB/s eta 0:00:23
   -------- ------------------------------- 2.1/9.5 MB 329.6 kB/s eta 0:00:23
   -------- ------------------------------- 2.1/9.5 MB 329.6 kB/s eta 0:00:23
   -------- ------------------------------- 2.1/9.5 MB 329.6 kB/s eta 0:00:23
   --------- ------------------------------ 2.4/9.5 MB 243.4 kB/s eta 0:00:30
   --------- ------------------------------ 2.4/9.5 MB 243.4 kB/s eta 0:00:30
   --------- ------------------------------ 2.4/9.5 MB 243.4 kB/s eta 0:00:30
   --------- ------------------------------ 2.4/9.5 MB 243.4 kB/s eta 0:00:30
   --------- ------------------------------ 2.4/9.5 MB 243.4 kB/s eta 0:00:30
   --------- ------------------------------ 2.4/9.5 MB 243.4 kB/s eta 0:00:30
   --------- ------------------------------ 2.4/9.5 MB 243.4 kB/s eta 0:00:30
   --------- ------------------------------ 2.4/9.5 MB 243.4 kB/s eta 0:00:30
   --------- ------------------------------ 2.4/9.5 MB 243.4 kB/s eta 0:00:30
   --------- ------------------------------ 2.4/9.5 MB 243.4 kB/s eta 0:00:30
   --------- ------------------------------ 2.4/9.5 MB 243.4 kB/s eta 0:00:30
   --------- ------------------------------ 2.4/9.5 MB 243.4 kB/s eta 0:00:30
   --------- ------------------------------ 2.4/9.5 MB 243.4 kB/s eta 0:00:30
   --------- ------------------------------ 2.4/9.5 MB 243.4 kB/s eta 0:00:30
   ----------- ---------------------------- 2.6/9.5 MB 205.8 kB/s eta 0:00:34
   ----------- ---------------------------- 2.6/9.5 MB 205.8 kB/s eta 0:00:34
   ----------- ---------------------------- 2.6/9.5 MB 205.8 kB/s eta 0:00:34
   ----------- ---------------------------- 2.6/9.5 MB 205.8 kB/s eta 0:00:34
   ----------- ---------------------------- 2.6/9.5 MB 205.8 kB/s eta 0:00:34
   ----------- ---------------------------- 2.6/9.5 MB 205.8 kB/s eta 0:00:34
   ----------- ---------------------------- 2.6/9.5 MB 205.8 kB/s eta 0:00:34
   ------------ --------------------------- 2.9/9.5 MB 204.9 kB/s eta 0:00:33
   ------------ --------------------------- 2.9/9.5 MB 204.9 kB/s eta 0:00:33
   ------------ --------------------------- 2.9/9.5 MB 204.9 kB/s eta 0:00:33
   ------------ --------------------------- 2.9/9.5 MB 204.9 kB/s eta 0:00:33
   ------------- -------------------------- 3.1/9.5 MB 210.7 kB/s eta 0:00:31
   ------------- -------------------------- 3.1/9.5 MB 210.7 kB/s eta 0:00:31
   ------------- -------------------------- 3.1/9.5 MB 210.7 kB/s eta 0:00:31
   ------------- -------------------------- 3.1/9.5 MB 210.7 kB/s eta 0:00:31
   ------------- -------------------------- 3.1/9.5 MB 210.7 kB/s eta 0:00:31
   -------------- ------------------------- 3.4/9.5 MB 213.3 kB/s eta 0:00:29
   -------------- ------------------------- 3.4/9.5 MB 213.3 kB/s eta 0:00:29
   -------------- ------------------------- 3.4/9.5 MB 213.3 kB/s eta 0:00:29
   -------------- ------------------------- 3.4/9.5 MB 213.3 kB/s eta 0:00:29
   -------------- ------------------------- 3.4/9.5 MB 213.3 kB/s eta 0:00:29
   -------------- ------------------------- 3.4/9.5 MB 213.3 kB/s eta 0:00:29
   --------------- ------------------------ 3.7/9.5 MB 214.9 kB/s eta 0:00:28
   --------------- ------------------------ 3.7/9.5 MB 214.9 kB/s eta 0:00:28
   --------------- ------------------------ 3.7/9.5 MB 214.9 kB/s eta 0:00:28
   --------------- ------------------------ 3.7/9.5 MB 214.9 kB/s eta 0:00:28
   --------------- ------------------------ 3.7/9.5 MB 214.9 kB/s eta 0:00:28
   ---------------- ----------------------- 3.9/9.5 MB 216.7 kB/s eta 0:00:26
   ---------------- ----------------------- 3.9/9.5 MB 216.7 kB/s eta 0:00:26
   ---------------- ----------------------- 3.9/9.5 MB 216.7 kB/s eta 0:00:26
   ---------------- ----------------------- 3.9/9.5 MB 216.7 kB/s eta 0:00:26
   ---------------- ----------------------- 3.9/9.5 MB 216.7 kB/s eta 0:00:26
   ---------------- ----------------------- 3.9/9.5 MB 216.7 kB/s eta 0:00:26
   ---------------- ----------------------- 3.9/9.5 MB 216.7 kB/s eta 0:00:26
   ----------------- ---------------------- 4.2/9.5 MB 213.3 kB/s eta 0:00:25
   ----------------- ---------------------- 4.2/9.5 MB 213.3 kB/s eta 0:00:25
   ----------------- ---------------------- 4.2/9.5 MB 213.3 kB/s eta 0:00:25
   ----------------- ---------------------- 4.2/9.5 MB 213.3 kB/s eta 0:00:25
   ----------------- ---------------------- 4.2/9.5 MB 213.3 kB/s eta 0:00:25
   ----------------- ---------------------- 4.2/9.5 MB 213.3 kB/s eta 0:00:25
   ----------------- ---------------------- 4.2/9.5 MB 213.3 kB/s eta 0:00:25
   ----------------- ---------------------- 4.2/9.5 MB 213.3 kB/s eta 0:00:25
   ----------------- ---------------------- 4.2/9.5 MB 213.3 kB/s eta 0:00:25
   ----------------- ---------------------- 4.2/9.5 MB 213.3 kB/s eta 0:00:25
   ----------------- ---------------------- 4.2/9.5 MB 213.3 kB/s eta 0:00:25
   ----------------- ---------------------- 4.2/9.5 MB 213.3 kB/s eta 0:00:25
   ----------------- ---------------------- 4.2/9.5 MB 213.3 kB/s eta 0:00:25
   ----------------- ---------------------- 4.2/9.5 MB 213.3 kB/s eta 0:00:25
   ----------------- ---------------------- 4.2/9.5 MB 213.3 kB/s eta 0:00:25
   ----------------- ---------------------- 4.2/9.5 MB 213.3 kB/s eta 0:00:25
   ------------------ --------------------- 4.5/9.5 MB 193.1 kB/s eta 0:00:27
   ------------------ --------------------- 4.5/9.5 MB 193.1 kB/s eta 0:00:27
   ------------------ --------------------- 4.5/9.5 MB 193.1 kB/s eta 0:00:27
   ------------------ --------------------- 4.5/9.5 MB 193.1 kB/s eta 0:00:27
   ------------------ --------------------- 4.5/9.5 MB 193.1 kB/s eta 0:00:27
   ------------------ --------------------- 4.5/9.5 MB 193.1 kB/s eta 0:00:27
   ------------------ --------------------- 4.5/9.5 MB 193.1 kB/s eta 0:00:27
   ------------------ --------------------- 4.5/9.5 MB 193.1 kB/s eta 0:00:27
   ------------------- -------------------- 4.7/9.5 MB 191.4 kB/s eta 0:00:26
   ------------------- -------------------- 4.7/9.5 MB 191.4 kB/s eta 0:00:26
   ------------------- -------------------- 4.7/9.5 MB 191.4 kB/s eta 0:00:26
   -------------------- ------------------- 5.0/9.5 MB 196.3 kB/s eta 0:00:24
   -------------------- ------------------- 5.0/9.5 MB 196.3 kB/s eta 0:00:24
   -------------------- ------------------- 5.0/9.5 MB 196.3 kB/s eta 0:00:24
   -------------------- ------------------- 5.0/9.5 MB 196.3 kB/s eta 0:00:24
   -------------------- ------------------- 5.0/9.5 MB 196.3 kB/s eta 0:00:24
   ---------------------- ----------------- 5.2/9.5 MB 199.3 kB/s eta 0:00:22
   ---------------------- ----------------- 5.2/9.5 MB 199.3 kB/s eta 0:00:22
   ---------------------- ----------------- 5.2/9.5 MB 199.3 kB/s eta 0:00:22
   ---------------------- ----------------- 5.2/9.5 MB 199.3 kB/s eta 0:00:22
   ---------------------- ----------------- 5.2/9.5 MB 199.3 kB/s eta 0:00:22
   ----------------------- ---------------- 5.5/9.5 MB 201.2 kB/s eta 0:00:20
   ----------------------- ---------------- 5.5/9.5 MB 201.2 kB/s eta 0:00:20
   ----------------------- ---------------- 5.5/9.5 MB 201.2 kB/s eta 0:00:20
   ----------------------- ---------------- 5.5/9.5 MB 201.2 kB/s eta 0:00:20
   ----------------------- ---------------- 5.5/9.5 MB 201.2 kB/s eta 0:00:20
   ----------------------- ---------------- 5.5/9.5 MB 201.2 kB/s eta 0:00:20
   ------------------------ --------------- 5.8/9.5 MB 202.3 kB/s eta 0:00:19
   ------------------------ --------------- 5.8/9.5 MB 202.3 kB/s eta 0:00:19
   ------------------------ --------------- 5.8/9.5 MB 202.3 kB/s eta 0:00:19
   ------------------------ --------------- 5.8/9.5 MB 202.3 kB/s eta 0:00:19
   ------------------------ --------------- 5.8/9.5 MB 202.3 kB/s eta 0:00:19
   ------------------------- -------------- 6.0/9.5 MB 203.5 kB/s eta 0:00:18
   ------------------------- -------------- 6.0/9.5 MB 203.5 kB/s eta 0:00:18
   ------------------------- -------------- 6.0/9.5 MB 203.5 kB/s eta 0:00:18
   ------------------------- -------------- 6.0/9.5 MB 203.5 kB/s eta 0:00:18
   ------------------------- -------------- 6.0/9.5 MB 203.5 kB/s eta 0:00:18
   ------------------------- -------------- 6.0/9.5 MB 203.5 kB/s eta 0:00:18
   ------------------------- -------------- 6.0/9.5 MB 203.5 kB/s eta 0:00:18
   ------------------------- -------------- 6.0/9.5 MB 203.5 kB/s eta 0:00:18
   ------------------------- -------------- 6.0/9.5 MB 203.5 kB/s eta 0:00:18
   -------------------------- ------------- 6.3/9.5 MB 192.5 kB/s eta 0:00:17
   -------------------------- ------------- 6.3/9.5 MB 192.5 kB/s eta 0:00:17
   -------------------------- ------------- 6.3/9.5 MB 192.5 kB/s eta 0:00:17
   -------------------------- ------------- 6.3/9.5 MB 192.5 kB/s eta 0:00:17
   -------------------------- ------------- 6.3/9.5 MB 192.5 kB/s eta 0:00:17
   -------------------------- ------------- 6.3/9.5 MB 192.5 kB/s eta 0:00:17
   --------------------------- ------------ 6.6/9.5 MB 170.9 kB/s eta 0:00:18
   --------------------------- ------------ 6.6/9.5 MB 170.9 kB/s eta 0:00:18
   --------------------------- ------------ 6.6/9.5 MB 170.9 kB/s eta 0:00:18
   --------------------------- ------------ 6.6/9.5 MB 170.9 kB/s eta 0:00:18
   --------------------------- ------------ 6.6/9.5 MB 170.9 kB/s eta 0:00:18
   --------------------------- ------------ 6.6/9.5 MB 170.9 kB/s eta 0:00:18
   ---------------------------- ----------- 6.8/9.5 MB 170.1 kB/s eta 0:00:16
   ---------------------------- ----------- 6.8/9.5 MB 170.1 kB/s eta 0:00:16
   ---------------------------- ----------- 6.8/9.5 MB 170.1 kB/s eta 0:00:16
   ---------------------------- ----------- 6.8/9.5 MB 170.1 kB/s eta 0:00:16
   ---------------------------- ----------- 6.8/9.5 MB 170.1 kB/s eta 0:00:16
   ---------------------------- ----------- 6.8/9.5 MB 170.1 kB/s eta 0:00:16
   ---------------------------- ----------- 6.8/9.5 MB 170.1 kB/s eta 0:00:16
   ----------------------------- ---------- 7.1/9.5 MB 174.2 kB/s eta 0:00:14
   ----------------------------- ---------- 7.1/9.5 MB 174.2 kB/s eta 0:00:14
   ----------------------------- ---------- 7.1/9.5 MB 174.2 kB/s eta 0:00:14
   ----------------------------- ---------- 7.1/9.5 MB 174.2 kB/s eta 0:00:14
   ----------------------------- ---------- 7.1/9.5 MB 174.2 kB/s eta 0:00:14
   ----------------------------- ---------- 7.1/9.5 MB 174.2 kB/s eta 0:00:14
   ------------------------------ --------- 7.3/9.5 MB 176.1 kB/s eta 0:00:13
   ------------------------------ --------- 7.3/9.5 MB 176.1 kB/s eta 0:00:13
   ------------------------------ --------- 7.3/9.5 MB 176.1 kB/s eta 0:00:13
   ------------------------------ --------- 7.3/9.5 MB 176.1 kB/s eta 0:00:13
   ------------------------------ --------- 7.3/9.5 MB 176.1 kB/s eta 0:00:13
   ------------------------------- -------- 7.6/9.5 MB 188.3 kB/s eta 0:00:11
   ------------------------------- -------- 7.6/9.5 MB 188.3 kB/s eta 0:00:11
   ------------------------------- -------- 7.6/9.5 MB 188.3 kB/s eta 0:00:11
   ------------------------------- -------- 7.6/9.5 MB 188.3 kB/s eta 0:00:11
   ------------------------------- -------- 7.6/9.5 MB 188.3 kB/s eta 0:00:11
   --------------------------------- ------ 7.9/9.5 MB 190.8 kB/s eta 0:00:09
   --------------------------------- ------ 7.9/9.5 MB 190.8 kB/s eta 0:00:09
   --------------------------------- ------ 7.9/9.5 MB 190.8 kB/s eta 0:00:09
   --------------------------------- ------ 7.9/9.5 MB 190.8 kB/s eta 0:00:09
   --------------------------------- ------ 7.9/9.5 MB 190.8 kB/s eta 0:00:09
   --------------------------------- ------ 7.9/9.5 MB 190.8 kB/s eta 0:00:09
   ---------------------------------- ----- 8.1/9.5 MB 192.3 kB/s eta 0:00:08
   ---------------------------------- ----- 8.1/9.5 MB 192.3 kB/s eta 0:00:08
   ---------------------------------- ----- 8.1/9.5 MB 192.3 kB/s eta 0:00:08
   ---------------------------------- ----- 8.1/9.5 MB 192.3 kB/s eta 0:00:08
   ---------------------------------- ----- 8.1/9.5 MB 192.3 kB/s eta 0:00:08
   ---------------------------------- ----- 8.1/9.5 MB 192.3 kB/s eta 0:00:08
   ----------------------------------- ---- 8.4/9.5 MB 203.1 kB/s eta 0:00:06
   ----------------------------------- ---- 8.4/9.5 MB 203.1 kB/s eta 0:00:06
   ----------------------------------- ---- 8.4/9.5 MB 203.1 kB/s eta 0:00:06
   ----------------------------------- ---- 8.4/9.5 MB 203.1 kB/s eta 0:00:06
   ----------------------------------- ---- 8.4/9.5 MB 203.1 kB/s eta 0:00:06
   ----------------------------------- ---- 8.4/9.5 MB 203.1 kB/s eta 0:00:06
   ------------------------------------ --- 8.7/9.5 MB 203.3 kB/s eta 0:00:05
   ------------------------------------ --- 8.7/9.5 MB 203.3 kB/s eta 0:00:05
   ------------------------------------ --- 8.7/9.5 MB 203.3 kB/s eta 0:00:05
   ------------------------------------ --- 8.7/9.5 MB 203.3 kB/s eta 0:00:05
   ------------------------------------ --- 8.7/9.5 MB 203.3 kB/s eta 0:00:05
   ------------------------------------ --- 8.7/9.5 MB 203.3 kB/s eta 0:00:05
   ------------------------------------- -- 8.9/9.5 MB 204.0 kB/s eta 0:00:03
   ------------------------------------- -- 8.9/9.5 MB 204.0 kB/s eta 0:00:03
   ------------------------------------- -- 8.9/9.5 MB 204.0 kB/s eta 0:00:03
   ------------------------------------- -- 8.9/9.5 MB 204.0 kB/s eta 0:00:03
   ------------------------------------- -- 8.9/9.5 MB 204.0 kB/s eta 0:00:03
   ------------------------------------- -- 8.9/9.5 MB 204.0 kB/s eta 0:00:03
   -------------------------------------- - 9.2/9.5 MB 201.9 kB/s eta 0:00:02
   -------------------------------------- - 9.2/9.5 MB 201.9 kB/s eta 0:00:02
   -------------------------------------- - 9.2/9.5 MB 201.9 kB/s eta 0:00:02
   -------------------------------------- - 9.2/9.5 MB 201.9 kB/s eta 0:00:02
   -------------------------------------- - 9.2/9.5 MB 201.9 kB/s eta 0:00:02
   -------------------------------------- - 9.2/9.5 MB 201.9 kB/s eta 0:00:02
   -------------------------------------- - 9.2/9.5 MB 201.9 kB/s eta 0:00:02
   ---------------------------------------  9.4/9.5 MB 197.6 kB/s eta 0:00:01
   ---------------------------------------  9.4/9.5 MB 197.6 kB/s eta 0:00:01
   ---------------------------------------  9.4/9.5 MB 197.6 kB/s eta 0:00:01
   ---------------------------------------- 9.5/9.5 MB 196.3 kB/s  0:00:45
Downloading trio-0.34.0-py3-none-any.whl (511 kB)
Downloading trio_websocket-0.12.2-py3-none-any.whl (21 kB)
Downloading PySocks-1.7.1-py3-none-any.whl (16 kB)

In [19]:
from selenium import webdriver

In [20]:
driver = webdriver.Chrome()

In [21]:
driver.get("https://www.imdb.com/chart/top/")

In [25]:
movies = driver.find_elements(
    "css selector",
    "li.ipc-metadata-list-summary-item"
)

print(len(movies))

250

In [26]:
ranks = []
movie_names = []

for movie in movies:
    rank = movie.find_element("css selector", "div.ipc-signpost__text").text
    name = movie.find_element("css selector", "h4.ipc-title__text").text

    ranks.append(rank.replace("#", ""))
    movie_names.append(name)

print(ranks[:5])
print(movie_names[:5])

['1', '2', '3', '4', '5']
['The Shawshank Redemption', 'The Godfather', 'The Dark Knight', 'The Godfather Part II', 'The Lord of the Rings: The Return of the King']

In [27]:
df = pd.DataFrame({
    "Rank": ranks,
    "Movie Name": movie_names
})

df.head()

  Rank                                     Movie Name
0    1                       The Shawshank Redemption
1    2                                  The Godfather
2    3                                The Dark Knight
3    4                          The Godfather Part II
4    5  The Lord of the Rings: The Return of the King

In [28]:
print(df.shape)

(250, 2)

In [29]:
df.head()

  Rank                                     Movie Name
0    1                       The Shawshank Redemption
1    2                                  The Godfather
2    3                                The Dark Knight
3    4                          The Godfather Part II
4    5  The Lord of the Rings: The Return of the King

In [30]:
df

    Rank                                     Movie Name
0      1                       The Shawshank Redemption
1      2                                  The Godfather
2      3                                The Dark Knight
3      4                          The Godfather Part II
4      5  The Lord of the Rings: The Return of the King
..   ...                                            ...
245  246                          The Battle of Algiers
246  247                           My Father and My Son
247  248                     The Passion of Joan of Arc
248  249                                 The Handmaiden
249  250                                  Autumn Sonata

[250 rows x 2 columns]

In [31]:
print(df.shape)

(250, 2)

In [32]:
df = pd.DataFrame({
    "Rank": ranks,
    "Movie Name": movie_names
})

In [33]:
df.to_csv("imdb_top_250_rank_movie_name.csv", index=False)